config/routes.rb
Survey::Engine.routes.draw do
	resources :survey_question_categories
	resources :survey_question_set_items
	resources :survey_validations
	resources :survey_questions do
		collection do
			get 'get_questions'
		end
	end
	resources :survey_question_sets do
		collection do
			get 'get_question_sets'
			get 'add_condition'
		end
	end
	resources :survey_evaluations, :except => [ :new, :show ] do
		collection do
			get 'evaluate_question'
			get 'add_condition_reference'
			get 'get_evaluations'
		end
	end
	root :to => 'survey_evaluations#index'
end

app/models/survey/survey_evaluation.rb
#app/models/survey_evaluation.rb
module Survey
	class SurveyEvaluation < ActiveRecord::Base
		set_table_name "survey_evaluations"

		attr_accessible :question_set_id, :status, :user_id, :evaluation_items_attributes

		has_many :evaluation_items, :class_name => "SurveyEvaluationItem", :foreign_key => :evaluation_id

		belongs_to :question_set, :class_name => "SurveyQuestionSet", :foreign_key => :question_set_id
    belongs_to :user, :class_name => USER_RESOURCE

		accepts_nested_attributes_for :evaluation_items,
																	:reject_if => proc { |attributes| attributes['answer_text'].blank? }

		validates :question_set_id, :presence => true
		#validates :status, :presence => true, :inclusion => { :in => ['started', 'completed']}
		validates_associated :evaluation_items
	end
end

app/models/survey/survey_question_category.rb
#app/models/survey/survey_question_category.rb

module Survey
	class SurveyQuestionCategory < ActiveRecord::Base
		set_table_name "survey_question_categories"

		attr_accessible :title, :parent_id

		has_many :children, :class_name => "SurveyQuestionCategory", :dependent => :destroy, :foreign_key => "parent_id"
		belongs_to :parent, :class_name => "SurveyQuestionCategory"
		has_many :questions, :class_name => "SurveyQuestion", :foreign_key => "question_category_id", :dependent => :destroy

		#scope :parents, where("parent_id IS NULL")

		validates :title, :presence => true, :length => { :maximum => 50 }, :uniqueness => { :case_sensitive => false }

		def descendants
		  all = []
		  self.children.each do |category|
		    all << category.id
		    root_children = category.descendants.flatten
		    all << root_children unless root_children.empty?
		  end
		  return all.flatten
		
		end

	end
end

app/models/survey/survey_question_selection.rb
#app/models/survey/survey_question_selection.rb

module Survey
	class SurveyQuestionSelection < ActiveRecord::Base
		set_table_name "survey_question_selections"

		attr_accessible :question_id, :text

		belongs_to :question, :class_name => "SurveyQuestion", :foreign_key => :question_id

		has_many :condition_selections, :class_name => "SurveyQuestionSetItemConditionSelection",
						 :foreign_key => :condition_id
		has_many :item_conditions, :class_name => "SurveyQuestionSetItemCondition", :through => :condition_selections
	
		validates :question, :presence => true
		validates :text, :presence => true
	end
end

app/models/survey/survey_question_set_item_condition_selection.rb
#app/models/survey/survey_question_set_item_condition_selection.rb

module Survey
	class SurveyQuestionSetItemConditionSelection < ActiveRecord::Base
		set_table_name "survey_question_set_item_condition_selections"

		attr_accessible :condition_id, :selection_id

		belongs_to :item_condition, :class_name => "SurveyQuestionSetItemCondition", :foreign_key => :condition_id
		belongs_to :selection, :class_name => "SurveyQuestionSelection", :foreign_key => :selection_id

		validates :item_condition, :presence => true
		validates :selection_id, :presence => true
	end
end

app/controllers/survey/application_controller.rb
module Survey
  class ApplicationController < ::ApplicationController
    protect_from_forgery

    protected

      def redirect_unless_logged_in
        if defined?(super)
          super
        else
          unless user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          end
        end
      end

      def redirect_unless_admin
        if defined?(super)
          super
        else
          if !user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          elsif !current_user.admin?
            redirect_to main_app.root_path, :notice => 'You do not have permission to view this page.'
          end
        end
      end
  end
end

app/controllers/survey/survey_evaluations_controller.rb
#app/controllers/survey_evaluations_controller.rb

module Survey
	class SurveyEvaluationsController < ApplicationController
		before_filter :add_class
		before_filter :redirect_unless_logged_in

		unloadable #marks the class for reloading inbetween requests.

    def index
      @survey_question_sets = SurveyQuestionSet.where( "published = ? AND question_set_type = ?", true, 'Assembly')
      @survey_question_categories = SurveyQuestionCategory.all
    end

    def create
      @survey_question_set = SurveyQuestionSet.find( params[:question_set_id] )
      @survey_evaluation = @survey_question_set.evaluations.create!( {:status => params[:status], :user_id => current_user.id} )

      render :edit
    end

    def edit
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_question_set = @survey_evaluation.question_set

      respond_to do |format|
        format.js
        format.html
      end
    end

    def update
      @survey_evaluation = SurveyEvaluation.find( params[:id] )

      if @survey_evaluation.update_attributes( params[:survey_evaluation] )
        flash[:notice] = "Survey Evaluation updated successfully!"
        redirect_to survey_evaluations_path
      else
        @survey_evaluation = SurveyEvaluation.find( params[:id] )
        @survey_question_set = @survey_evaluation.question_set
        render 'edit'
      end
    end

    def destroy
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_evaluation.destroy
      flash[:notice] = "Survey Evaluation successfully destroyed!"
      redirect_to survey_evaluations_path
    end

    def evaluate_question
      items = params[:item_id].include?('_') ? nil : SurveyQuestionSetItem.where(:id => params[:item_id])
      @level = params[:level] ? params[:level] : 1
      @object = params[:object].nil? ? "survey_evaluation[evaluation_items_attributes]" : params[:object] + "[children_attributes]"
      @evaluation = SurveyEvaluation.find( params[:eval_id] ) if params[:eval_id]

      unless items.blank?
        @question_set_item = items.first
        if @question_set_item.question_reference_type == "Survey::SurveyQuestion"
          @question = @question_set_item.question_reference
        end

        if @evaluation
          @evaluation_item = @evaluation.evaluation_items.where('question_id = ? AND level = ? AND question_set_item_id = ?', @question.id, @level, @question_set_item.id ).first
        else
          @evaluation_item = SurveyEvaluationItem.where('question_id = ? AND level = ? AND question_set_item_id = ?',
                                                      @question.id, @level, @question_set_item.id ).first
        end
      end

      @question = SurveyQuestion.find( params[:question_id] ) if params[:question_id]
      @item_id = params[:item_id]

      if @evaluation_item.blank?
      	if @evaluation && params[:question_id]
      		@evaluation_item = @evaluation.evaluation_items
      			.where('question_id = ? AND level = ? AND question_set_item_id IS NULL',
      				 params[:question_id], @level ).first
      	else
        	@evaluation_item = SurveyEvaluationItem.new
        end
      end

      if @question.question_type == "Text Box"
        @question_validations = @question.survey_question_validations
      else
        @question_selections = @question.selections
      end

      respond_to do |format|
        format.js
      end

    end

    def add_condition_reference
      @question_set_item = SurveyQuestionSetItem.find( params[:item_id] )
      eval_item = SurveyEvaluationItem.new
      @conditions = []
      @level = params[:level].to_i + 1;
      @object = params[:object]
      @selected_value = params[:text].kind_of?(Array) ? params[:text].join('-') : params[:text]
      unless @question_set_item.nil?
        @valid = true
        @errors = []
        @question_set_item.item_conditions.each do |condition|
          if @question_set_item.question_reference.question_type == "Text Box"
            @param_list = []
            @param_list << params[:text]
            condition.condition_validations.each do |condition_val|
              @param_list << condition_val.validation_param_1 if condition_val.validation_param_1
              @param_list << condition_val.validation_param_2 if condition_val.validation_param_2
              validation_method = condition_val.item_validation.title
              unless eval_item.send validation_method, @param_list
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          
          elsif @question_set_item.question_reference.question_type != "Text Box(Date)"
          	selections = []
            condition.condition_selections.each do |condition_selection|
              selections << condition_selection.selection_id.to_s
            end
            
            if params[:text].kind_of?(Array)
              @size = params[:text].join(',')
              unless selections.sort! == params[:text].sort!
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            else
            	puts selections.inspect
            	puts '###'+params[:text]
              unless selections.include?(params[:text])
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          end
        end

      end
    end

    def get_evaluations
      @survey_question_set = SurveyQuestionSet.find(params[:set_id])
      @evaluations = @survey_question_set.evaluations.where('user_id = ?', current_user.id)

      respond_to do |format|
        format.js
      end
    end

    private

      def add_class
        @html_class = "survey_evaluation"
      end
  end
end

app/controllers/survey/survey_question_categories_controller.rb
#app/controllers/survey_question_categories_controller.rb

module Survey
	class SurveyQuestionCategoriesController < ApplicationController
		before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Categories"
      @survey_question_categories = SurveyQuestionCategory.all

      respond_to do |format|
        format.js { @set_id = params[:id] }
      end
    end

    def new
      @title = "Add Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.new
    end

    def create
      @survey_question_category =  SurveyQuestionCategory.new( params[:survey_question_category] )
      @facebox_id = params[:facebox_id]

      if @survey_question_category.save
        flash[:notice] = "Survey Question Category created successfully!"
        respond_to do |format|
          format.js {render :js => "window.location = '" + request.referer + "';"}
        end
      else
        @title = "Add Survey Question Categories"
        respond_to do |format|
          format.js { render 'new' }
        end
      end

    end

    def edit
      @title = "Edit Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )
    end

    def update
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )

      if @survey_question_category.update_attributes( params[:survey_question_category] )
        flash[:notice] = "Survey Question Category updated successfully!"
        redirect_to survey_question_categories_path
      else
        @title = "Edit Survey Question Categories"
        render 'edit'
      end

    end

    def get_conditions_form
      respond_to do |format|
        format.js
      end
    end

	end
end

app/controllers/survey/survey_question_set_items_controller.rb
#app/controllers/survey_question_set_items_controller.rb

module Survey
	class SurveyQuestionSetItemsController < ApplicationController
    before_filter :redirect_unless_logged_in
    before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Set Items"
      @survey_question_set_items = SurveyQuestionSetItem.all
    end

    def new
      @title = "Add Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.new
    end

    def create
      @survey_question_set_item = SurveyQuestionSetItem.new( params[:survey_question_set_item] )

      if @survey_question_set_item.save
        flash[:notice] = "Survey Question Set Item created successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Add Survey Question Set Item"
        render 'new'
      end

    end

    def edit
      @title = "Edit Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
    end

    def update
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )

      if @survey_question_set_item.update_attributes( params[:survey_question_set_item] )
        flash[:notice] = "Survey Question Set Item updated successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Edit Survey Question Item"
        render 'edit'
      end
    end

    def destroy
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
      @survey_question_set_item.destroy

      flash[:notice] = "Survey Question Set Item destroyed successfully!"
      redirect_to survey_question_set_items_path
    end

	end
end

app/controllers/survey/survey_validations_controller.rb
class SurveyValidationsController < ApplicationController
  def index
  end

end

app/helpers/survey/application_helper.rb
module Survey
	module ApplicationHelper

		# Return a title on a page
    def title
      base_title = "Mindfire Survey"
      if @title.nil?
        base_title
      else
        "#{@title} | #{base_title}"
      end
    end

    #return the logo of the app
    def logo
      image_tag( "rails.png", :alt => "Survey", :class => "round" )
    end

    #return the validations list
    def setup_question

      ( SurveyValidation.all - @survey_question.validations ).each do |validation|
        @survey_question.survey_question_validations.build(:validation => validation)
      end

      @survey_question.selections.build if @survey_question.selections.nil?
      @survey_question
      #question/tmp/clean-controllers.md.html
    end

    def evaluate_sets( set, return_string = "", level = 1 )
      return_string += '<ul class="hierarchy">'
      set.items.each do |item|
        return_string += '<li>'
        return_string += evaluate_item(item, level)
        return_string += '</li>'
      end
      return_string += '</ul>'
    end

    def evaluate_ref(evaluation_id, item)
      eval_item = item.evaluation_items.find_by_evaluation_id(evaluation_id)
      return_string = ''
      
      unless eval_item.blank?
        eval_item.children.each do |child|
          return_string += '<ul class="reference">'
          return_string += '<li>'
          
          if child.set_item
            return_string += evaluate_item(child.set_item, child.level, eval_item)
          else
            return_string += evaluate_item(child.question, child.level, eval_item)
          end
          
          return_string += '</li>'
          return_string += '</ul>'
        end
      end
      return return_string
    end

    def evaluate_item(item, level, parent_item = nil)
      return_string = ''

      if item.class.name == "Survey::SurveyQuestion"
      	item_id = parent_item.question_set_item_id.to_s + '_opt'
      	item_id += parent_item.answer_text.gsub(',', '-') + '_q' + item.id.to_s
        return_string += '<span class="title item_'+item_id+'">' + hidden_field_tag("item_id", item_id)
        return_string += hidden_field_tag("question_id", item.id)
        return_string += hidden_field_tag("level", level)
        return_string += hidden_field_tag("object", @object) unless @object.nil?
        return_string += item.text + '</span>'
      elsif item.question_reference_type == "Survey::SurveyQuestionSet"
        return_string += '<span class="expand_or_collapse">'
        return_string +=		'<span class="expand">[+]</span>'
        return_string +=		'<span class="collapse">[-]</span>'
        return_string +=	'</span>'
        return_string +=  '<span class="title">' + item.question_reference.title.to_s + '</span>'
        return_string += evaluate_sets( item.question_reference, '', level )
      else
        return_string += '<span class="title item_'+item.id.to_s+'">' + hidden_field_tag( "item_id", item.id )
        return_string += hidden_field_tag( "level", level )
        return_string += hidden_field_tag( "object", @object ) unless @object.nil?
        return_string += item.question_reference.text.to_s + '</span>'

        return_string += evaluate_ref(@survey_evaluation.id, item) if @survey_evaluation
      end

      return return_string
    end
	end
end

app/views/survey/survey_question_sets/_choose_items.html.erb
<div class="choose_from">
  <%= radio_button_tag "choose_from", "all", true %>
  <%= label_tag :choose_from_all, "All Categories" %>
  <%= radio_button_tag "choose_from", "category" %>
  <%= label_tag :choose_from_category, "Select Category" %>

  <div id="list_question_categories"></div>
</div>

<div class="show_category_items">
  <div class="tabs">
    <span id="questions" class="tab selected">Questions</span>

    <span id="question_sets" class="tab">Question Sets</span>
  </div>

  <div id="show_questions">
    <%= render 'survey/survey_questions/questions',
      :question_index => question_index %>
  </div>
  
  <div id="show_question_sets" class="hidden">
    <%= render 'question_sets', :question_index => question_index %>
  </div>
</div>
<div class="clr_float"></div>

app/views/survey/survey_question_sets/_condition_fields.html.erb
<% if @selected_question.question_type == "Text Box(Date)" %>
  No Condition can be added for questions with dates.
<% else %>
<% index ||= "__index__"%>

<div id="condition_<%= index %>" class="condition_fields condition_for_<%= @selected_question.id %>">
  <%= f.fields_for "item_conditions_attributes", :index => index do |ff| %>

    <% if !@survey_question_set.nil? && !@survey_question_set.published %>
      <%= ff.hidden_field :id, :value => condition.id, :class => "id_field" %>
      <%= ff.hidden_field :_destroy, :value => 0, :class => "destroy_field" %>
    <% end %>

    <div class="fields">
      <%= ff.label :title %>
      <%= ff.text_field :title, :class => 'condition_title',
        :value => condition.title %>
    </div>

    <div class="fields">
      <%= label_tag "reference", "Reference to" %> :

      <%= ff.radio_button :reference_type, "1",
        :checked => ( condition.reference_type != 2 ),
        :class => 'condition_reference_type' %>
      <%= ff.label :reference_type_1, "Question" %>

      <%= ff.radio_button :reference_type, "2",
        :checked => ( condition.reference_type == 2 ),
        :class => 'condition_reference_type' %>
      <%= ff.label :reference_type_2, "Question Set" %>
    </div>

    <div class="fields">
      <%= ff.label :reference_id, "Reference" %> :

      <% if condition.reference_type == 2 %>
        <% @reference = Survey::SurveyQuestionSet.where('published = ?', true) %>
        <%= ff.collection_select :reference_id, @reference, :id,
          :title_with_version, {:selected => condition.reference_id},
          :class => "condition_reference" %>
      <% else %>
        <% @reference = Survey::SurveyQuestion.where('published = ?', true) %>
        <%= ff.collection_select :reference_id, @reference, :id,
          :title_with_version, {:selected => condition.reference_id},
          :class => "condition_reference" %>
      <% end %>
    </div>

    <div class="fields">
      <% if @selected_question.question_type == "Text Box" %>
        <%= render 'survey/shared/validations', :f => ff, :condition => condition,
          :index => index %>
      <% else %>
        <% if @selected_question.question_type != "Text Box(Date)" %>
          <%= render 'survey/shared/selections', :f => ff, :condition => condition,
            :index => index %>
        <% end %>
      <% end %>
    </div>

    <div class="actions">
      <%= button_tag "Save Condition", :name => 'action', :value => 'add',
        :question => @selected_question.id %>
      <%= button_tag "Cancel", :name => 'action', :value => 'cancel' %>
    </div>

  <% end %>
</div>
<% end %>

app/views/survey/survey_question_sets/_fields.html.erb
<%= render 'survey/shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :category %>
  <%= f.collection_select( :question_category_id, @categories, :id, :title ) %>
</div>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :question_set_type %>
  <% @question_set_types = [ "Assembly", "Sub-assembly" ] %>
  <%= f.select :question_set_type, @question_set_types %>
</div>

<div class="field">
  <label> Version :
    <% version = @survey_question_set.add_version %>
    <%= version %>
    <%= f.hidden_field :version, :value => version %>
  </label>

  <%= f.check_box :published, {}, true, false %>
  <%= f.label :published %>
  <%= f.check_box :active, {}, true, false %>
  <%= f.label :active %>
</div>

<div class="tabs">
  <span id="choose_items" class="tab selected">Choose</span>
  <span id="selected_items" class="tab">Selected</span>
</div>

<% question_index = Hash.new %>

<div id="show_choose_items">
  <%= render 'choose_items', :question_index => question_index %>
</div>

<div id="hidden_conditions">
    <%
      unless @survey_question_set.new_record?
        index = 0
        @item_conditions = Hash.new
        @survey_question_set.items.each do |item|
          if item.question_reference_type == "Survey::SurveyQuestion"
            @item_conditions[item.question_reference_id] = Hash.new
            item.item_conditions.each do |condition|
              @field_object = @condition_object[item.id]
              builder = ActionView::Helpers::FormBuilder.new( "#{@field_object}",
                                                      condition, self, {}, proc {})
              @selected_question = item.question_reference
    %>

    <%= render 'condition_fields', :f => builder, :index => index,
                    :condition => condition, :field_object => @field_object %>
    <%
              @item_conditions[item.question_reference_id][index] = condition.title
              index += 1
            end
          end
        end
      end
    %>
</div>

<div id="show_selected_items" class="hidden">
  <%= render 'selected_items', :f => f, :question_index => question_index %>
</div>

app/views/survey/survey_question_sets/_question_sets.html.erb
<ul>
  <li></li>
  <%
    i = (Time.now.to_f * 1000).to_i
    @survey_question_sets.each do |set|
      checked = false
      item_id = nil

      unless @survey_question_set.nil?
        unless set.question_set_items.nil?
          @survey_question_set.items.each do |item|
            if item.question_reference_type == "Survey::SurveyQuestionSet" && item.question_reference == set
              item_id = item.id
              checked =  true
              question_index[item.id] = i
              break
            end
          end
        end
      end
  %>

    <li class="question_set">

      <% if !@survey_question_set.published && !item_id.nil? %>
        <%= hidden_field "survey_question_set[items_attributes][" + "#{i}" + "]", "id",
          :value => item_id, :class => "id_field" %>

        <%= hidden_field "survey_question_set[items_attributes][" + "#{i}" + "]", "_destroy",
          :value => 0, :class => "destroy_field" %>
      <% end %>

      <%= hidden_field "survey_question_set[items_attributes]["+i.to_s+"]", "question_reference_type",
        :value => "Survey::SurveyQuestionSet", :class => "item_type" %>
      
      <%= check_box_tag("survey_question_set[items_attributes][#{i.to_s}][question_reference_id]",
        set.id, checked ) %>

      <%= label_tag( "survey_question_set_items_attriutes_#{i.to_s}_question_reference_id",
        set.title + " (" + set.version + ")" ) %>
      
      <% i += 1 %>

    </li>
  <% end %>
</ul>

app/views/survey/survey_question_sets/_selected_items.html.erb
<ul class="items">
  <li>Title</li>
  <%
    unless @survey_question_set.items.blank?
      @survey_question_set.items.each do |item|
        if item.question_reference_type == "Survey::SurveyQuestion"
  %>
          <li>
            <span class="title">

              <% if !@survey_question_set.published %>
                <%= hidden_field_tag "survey_question_set[items_attributes][" + "#{question_index[item.id]}" + "][id]", item.id, :class => "id_field" %>

                <%= hidden_field_tag "survey_question_set[items_attributes][" + "#{question_index[item.id]}" + "][_destroy]", 0, :class => "destroy_field" %>

              <% end %>

              <%= hidden_field_tag "survey_question_set[items_attributes][" + "#{question_index[item.id]}" + "][question_reference_type]",
                "Survey::SurveyQuestion", :class => "item_type" %>

              <%= check_box_tag( "survey_question_set[items_attributes][" + "#{question_index[item.id]}" + "][question_reference_id]",
                item.question_reference_id, true ) %>

              <%= label_tag( "survey_question_set_items_attriutes_#{question_index[item.id]}_question_reference_id",
                item.question_reference.text + " (" + item.question_reference.version + ")" ) %>

            </span>

            <span class="item_type"> question </span>

            <span class="actions"><a href="#" class="remove_item"> remove </a></span>
          </li>
  <%
        else
          if item.question_reference_type == "Survey::SurveyQuestionSet"
  %>
            <li class="question_set">
              <span class="title">
                <% quest_index = question_index[item.id].to_s %>
                <% if !@survey_question_set.published %>
                  <%= hidden_field_tag "survey_question_set[items_attributes][" + quest_index + "][id]", item.id, :class => "id_field" %>

                  <%= hidden_field_tag "survey_question_set[items_attributes][" + quest_index + "][_destroy]", 0, :class => "destroy_field" %>
                <% end %>

                <%= hidden_field_tag "survey_question_set[items_attributes][" + quest_index + "[question_reference_type]",
                  "Survey::SurveyQuestionSet", :class => "item_type" %>

                <%= check_box_tag("survey_question_set[items_attributes][#{question_index[item.id]}][question_reference_id]",
                  item.question_reference_id, true ) %>
                <%= label_tag( "survey_question_set_items_attriutes_#{question_index[item.id]}_question_reference_id",
                  item.question_reference.title + " (" + item.question_reference.version + ")" ) %>
              </span>

              <span class="item_type"> question_set </span>

              <span class="actions"><a href="#" class="remove_item"> remove </a></span>
            </li>
  <%
          end
        end
      end
    end
  %>
</ul>
<div class="item_conditions">
    <span class="add_link">
      <%= link_to  "Add Condition", '#', :class => "add_condition" %>
    </span>

    <% unless @item_conditions.nil? %>
      <% @item_conditions.each do |id, conditions| %>
        <div id="item_<%= id %>" class="conditions_container">

        <% conditions.each do |index, condition| %>
          <div class="conditions <%= index %> <%= condition.parameterize %>">
            <span class="title">
              <%= condition %>
            </span>

            <span class="actions">
              <%= link_to "edit", "#", :class => "edit_condition", :condition => index %>
            </span>

            <span class="actions">
              <%= link_to "remove", "#", :class => "remove_condition", :condition => index %>
            </span>

          </div>
        <% end %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/survey/survey_question_sets/_survey_question_set.html.erb
<tr>

  <% html_class = survey_question_set.published ? 'edit edit_published_set' : 'edit' %>
  <td class="question_set_title">
    <%= survey_question_set.title %>
  </td>

  <td>
    <%= survey_question_set.version %>
  </td>

  <td>
    <%= survey_question_set.published ? 'published' : 'draft' %>
  </td>

  <td class="actions">
    <%= link_to "Edit", edit_survey_question_set_path( survey_question_set ),
      :remote => true, :class => html_class, :title => "Edit question set" %>

      <% unless survey_question_set.published %>
        <%= link_to "Delete", survey_question_set_path( survey_question_set ),
          :method => :delete, :confirm => 'Are you sure?', :class => "delete",
          :title => "Delete question set" %>

      <% else %>
        <%= link_to "Delete", "#", :onclick => "return false",
          :class => "disabled_delete", :title => "Disabled" %>
      <% end %>
  </td>

</tr>

app/views/survey/survey_question_sets/add_condition.js.erb
<%
  condition = Survey::SurveyQuestionSetItemCondition.new
  builder = ActionView::Helpers::FormBuilder.new( "#{@object}", condition, self,
    {}, proc {})
%>
var index = new Date() * 1 + parseInt(Math.random()*100000);

function newCondition() {
  var basic = "<%= escape_javascript(render 'condition_fields', :f => builder, :condition => condition) %>";
  while (basic.indexOf("__index__") != -1) basic = basic.replace("__index__", index);
  return basic;
}

$.facebox(newCondition(), false, 'facebox' + index);
$('#facebox' + index + ' .content').css('width', '400px');
left = parseFloat($('#facebox' + index).css('left').substring(-2)) + 150;
$('#facebox' + index).css('left', left + 'px');
$('#edit_overlay').remove();

app/views/survey/survey_question_sets/index.html.erb
<div class="section survey_question_sets">
  <h1>Survey Question Sets</h1>

  <div class="categories">
    <%= link_to "All",
      { :controller => "survey_questions", :action => "get_questions",
        :category => "all", :item => "survey_question_set" },
      :remote => true, :id => "cat-all" %>

    <div class="add_category">
      <%= link_to "Add", new_survey_question_category_path, :remote => true,
        :title => "Add a new category" %>
    </div>

    <%= render 'survey/survey_question_categories/question_categories', :parent => nil,
      :item => 'survey_question_set' %>
  </div>

  <div class="list_content">
    <div class="add_question_set">
      <%= link_to "Add", new_survey_question_set_path, :remote => true, :title => "Add a new question set" %>
    </div>

    <table id="questions_list" class="survey_question_sets display">
      <thead>
        <th>Title</th>
        <th>Version</th>
        <th>Status</th>
        <th>Actions</th>
      </thead>

      <tbody>
        <%= render @survey_question_sets %>
      </tbody>
    </table>
  </div>
</div>