config/routes.rb
Survey::Engine.routes.draw do
	resources :survey_question_categories
	resources :survey_question_set_items
	resources :survey_validations
	resources :survey_questions do
		collection do
			get 'get_questions'
		end
	end
	resources :survey_question_sets do
		collection do
			get 'get_question_sets'
			get 'add_condition'
		end
	end
	resources :survey_evaluations, :except => [ :new, :show ] do
		collection do
			get 'evaluate_question'
			get 'add_condition_reference'
			get 'get_evaluations'
		end
	end
	root :to => 'survey_evaluations#index'
end

app/models/survey/survey_evaluation.rb
#app/models/survey_evaluation.rb
module Survey
	class SurveyEvaluation < ActiveRecord::Base
		set_table_name "survey_evaluations"

		attr_accessible :question_set_id, :status, :user_id, :evaluation_items_attributes

		has_many :evaluation_items, :class_name => "SurveyEvaluationItem", :foreign_key => :evaluation_id

		belongs_to :question_set, :class_name => "SurveyQuestionSet", :foreign_key => :question_set_id
    belongs_to :user, :class_name => USER_RESOURCE

		accepts_nested_attributes_for :evaluation_items,
																	:reject_if => proc { |attributes| attributes['answer_text'].blank? }

		validates :question_set_id, :presence => true
		#validates :status, :presence => true, :inclusion => { :in => ['started', 'completed']}
		validates_associated :evaluation_items
	end
end

app/models/survey/survey_question_category.rb
#app/models/survey/survey_question_category.rb

module Survey
	class SurveyQuestionCategory < ActiveRecord::Base
		set_table_name "survey_question_categories"

		attr_accessible :title, :parent_id

		has_many :children, :class_name => "SurveyQuestionCategory", :dependent => :destroy, :foreign_key => "parent_id"
		belongs_to :parent, :class_name => "SurveyQuestionCategory"
		has_many :questions, :class_name => "SurveyQuestion", :foreign_key => "question_category_id", :dependent => :destroy

		#scope :parents, where("parent_id IS NULL")

		validates :title, :presence => true, :length => { :maximum => 50 }, :uniqueness => { :case_sensitive => false }

		def descendants
		  all = []
		  self.children.each do |category|
		    all << category.id
		    root_children = category.descendants.flatten
		    all << root_children unless root_children.empty?
		  end
		  return all.flatten
		
		end

	end
end

app/models/survey/survey_question_selection.rb
#app/models/survey/survey_question_selection.rb

module Survey
	class SurveyQuestionSelection < ActiveRecord::Base
		set_table_name "survey_question_selections"

		attr_accessible :question_id, :text

		belongs_to :question, :class_name => "SurveyQuestion", :foreign_key => :question_id

		has_many :condition_selections, :class_name => "SurveyQuestionSetItemConditionSelection",
						 :foreign_key => :condition_id
		has_many :item_conditions, :class_name => "SurveyQuestionSetItemCondition", :through => :condition_selections
	
		validates :question, :presence => true
		validates :text, :presence => true
	end
end

app/models/survey/survey_question_set_item_condition_selection.rb
#app/models/survey/survey_question_set_item_condition_selection.rb

module Survey
	class SurveyQuestionSetItemConditionSelection < ActiveRecord::Base
		set_table_name "survey_question_set_item_condition_selections"

		attr_accessible :condition_id, :selection_id

		belongs_to :item_condition, :class_name => "SurveyQuestionSetItemCondition", :foreign_key => :condition_id
		belongs_to :selection, :class_name => "SurveyQuestionSelection", :foreign_key => :selection_id

		validates :item_condition, :presence => true
		validates :selection_id, :presence => true
	end
end

app/controllers/survey/application_controller.rb
module Survey
  class ApplicationController < ::ApplicationController
    protect_from_forgery

    protected

      def redirect_unless_logged_in
        if defined?(super)
          super
        else
          unless user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          end
        end
      end

      def redirect_unless_admin
        if defined?(super)
          super
        else
          if !user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          elsif !current_user.admin?
            redirect_to main_app.root_path, :notice => 'You do not have permission to view this page.'
          end
        end
      end
  end
end

app/controllers/survey/survey_evaluations_controller.rb
#app/controllers/survey_evaluations_controller.rb

module Survey
	class SurveyEvaluationsController < ApplicationController
		before_filter :add_class
		before_filter :redirect_unless_logged_in

		unloadable #marks the class for reloading inbetween requests.

    def index
      @survey_question_sets = SurveyQuestionSet.where( "published = ? AND question_set_type = ?", true, 'Assembly')
      @survey_question_categories = SurveyQuestionCategory.all
    end

    def create
      @survey_question_set = SurveyQuestionSet.find( params[:question_set_id] )
      @survey_evaluation = @survey_question_set.evaluations.create!( {:status => params[:status], :user_id => current_user.id} )

      render :edit
    end

    def edit
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_question_set = @survey_evaluation.question_set

      respond_to do |format|
        format.js
        format.html
      end
    end

    def update
      @survey_evaluation = SurveyEvaluation.find( params[:id] )

      if @survey_evaluation.update_attributes( params[:survey_evaluation] )
        flash[:notice] = "Survey Evaluation updated successfully!"
        redirect_to survey_evaluations_path
      else
        @survey_evaluation = SurveyEvaluation.find( params[:id] )
        @survey_question_set = @survey_evaluation.question_set
        render 'edit'
      end
    end

    def destroy
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_evaluation.destroy
      flash[:notice] = "Survey Evaluation successfully destroyed!"
      redirect_to survey_evaluations_path
    end

    def evaluate_question
      items = params[:item_id].include?('_') ? nil : SurveyQuestionSetItem.where(:id => params[:item_id])
      @level = params[:level] ? params[:level] : 1
      @object = params[:object].nil? ? "survey_evaluation[evaluation_items_attributes]" : params[:object] + "[children_attributes]"
      @evaluation = SurveyEvaluation.find( params[:eval_id] ) if params[:eval_id]

      unless items.blank?
        @question_set_item = items.first
        if @question_set_item.question_reference_type == "Survey::SurveyQuestion"
          @question = @question_set_item.question_reference
        end

        if @evaluation
          @evaluation_item = @evaluation.evaluation_items.where('question_id = ? AND level = ? AND question_set_item_id = ?', @question.id, @level, @question_set_item.id ).first
        else
          @evaluation_item = SurveyEvaluationItem.where('question_id = ? AND level = ? AND question_set_item_id = ?',
                                                      @question.id, @level, @question_set_item.id ).first
        end
      end

      @question = SurveyQuestion.find( params[:question_id] ) if params[:question_id]
      @item_id = params[:item_id]

      if @evaluation_item.blank?
      	if @evaluation && params[:question_id]
      		@evaluation_item = @evaluation.evaluation_items
      			.where('question_id = ? AND level = ? AND question_set_item_id IS NULL',
      				 params[:question_id], @level ).first
      	else
        	@evaluation_item = SurveyEvaluationItem.new
        end
      end

      if @question.question_type == "Text Box"
        @question_validations = @question.survey_question_validations
      else
        @question_selections = @question.selections
      end

      respond_to do |format|
        format.js
      end

    end

    def add_condition_reference
      @question_set_item = SurveyQuestionSetItem.find( params[:item_id] )
      eval_item = SurveyEvaluationItem.new
      @conditions = []
      @level = params[:level].to_i + 1;
      @object = params[:object]
      @selected_value = params[:text].kind_of?(Array) ? params[:text].join('-') : params[:text]
      unless @question_set_item.nil?
        @valid = true
        @errors = []
        @question_set_item.item_conditions.each do |condition|
          if @question_set_item.question_reference.question_type == "Text Box"
            @param_list = []
            @param_list << params[:text]
            condition.condition_validations.each do |condition_val|
              @param_list << condition_val.validation_param_1 if condition_val.validation_param_1
              @param_list << condition_val.validation_param_2 if condition_val.validation_param_2
              validation_method = condition_val.item_validation.title
              unless eval_item.send validation_method, @param_list
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          
          elsif @question_set_item.question_reference.question_type != "Text Box(Date)"
          	selections = []
            condition.condition_selections.each do |condition_selection|
              selections << condition_selection.selection_id.to_s
            end
            
            if params[:text].kind_of?(Array)
              @size = params[:text].join(',')
              unless selections.sort! == params[:text].sort!
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            else
            	puts selections.inspect
            	puts '###'+params[:text]
              unless selections.include?(params[:text])
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          end
        end

      end
    end

    def get_evaluations
      @survey_question_set = SurveyQuestionSet.find(params[:set_id])
      @evaluations = @survey_question_set.evaluations.where('user_id = ?', current_user.id)

      respond_to do |format|
        format.js
      end
    end

    private

      def add_class
        @html_class = "survey_evaluation"
      end
  end
end

app/controllers/survey/survey_question_categories_controller.rb
#app/controllers/survey_question_categories_controller.rb

module Survey
	class SurveyQuestionCategoriesController < ApplicationController
		before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Categories"
      @survey_question_categories = SurveyQuestionCategory.all

      respond_to do |format|
        format.js { @set_id = params[:id] }
      end
    end

    def new
      @title = "Add Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.new
    end

    def create
      @survey_question_category =  SurveyQuestionCategory.new( params[:survey_question_category] )
      @facebox_id = params[:facebox_id]

      if @survey_question_category.save
        flash[:notice] = "Survey Question Category created successfully!"
        respond_to do |format|
          format.js {render :js => "window.location = '" + request.referer + "';"}
        end
      else
        @title = "Add Survey Question Categories"
        respond_to do |format|
          format.js { render 'new' }
        end
      end

    end

    def edit
      @title = "Edit Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )
    end

    def update
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )

      if @survey_question_category.update_attributes( params[:survey_question_category] )
        flash[:notice] = "Survey Question Category updated successfully!"
        redirect_to survey_question_categories_path
      else
        @title = "Edit Survey Question Categories"
        render 'edit'
      end

    end

    def get_conditions_form
      respond_to do |format|
        format.js
      end
    end

	end
end

app/controllers/survey/survey_question_set_items_controller.rb
#app/controllers/survey_question_set_items_controller.rb

module Survey
	class SurveyQuestionSetItemsController < ApplicationController
    before_filter :redirect_unless_logged_in
    before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Set Items"
      @survey_question_set_items = SurveyQuestionSetItem.all
    end

    def new
      @title = "Add Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.new
    end

    def create
      @survey_question_set_item = SurveyQuestionSetItem.new( params[:survey_question_set_item] )

      if @survey_question_set_item.save
        flash[:notice] = "Survey Question Set Item created successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Add Survey Question Set Item"
        render 'new'
      end

    end

    def edit
      @title = "Edit Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
    end

    def update
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )

      if @survey_question_set_item.update_attributes( params[:survey_question_set_item] )
        flash[:notice] = "Survey Question Set Item updated successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Edit Survey Question Item"
        render 'edit'
      end
    end

    def destroy
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
      @survey_question_set_item.destroy

      flash[:notice] = "Survey Question Set Item destroyed successfully!"
      redirect_to survey_question_set_items_path
    end

	end
end

app/controllers/survey/survey_validations_controller.rb
class SurveyValidationsController < ApplicationController
  def index
  end

end

app/helpers/survey/application_helper.rb
module Survey
	module ApplicationHelper

		# Return a title on a page
    def title
      base_title = "Mindfire Survey"
      if @title.nil?
        base_title
      else
        "#{@title} | #{base_title}"
      end
    end

    #return the logo of the app
    def logo
      image_tag( "rails.png", :alt => "Survey", :class => "round" )
    end

    #return the validations list
    def setup_question

      ( SurveyValidation.all - @survey_question.validations ).each do |validation|
        @survey_question.survey_question_validations.build(:validation => validation)
      end

      @survey_question.selections.build if @survey_question.selections.nil?
      @survey_question
      #question/tmp/clean-controllers.md.html
    end

    def evaluate_sets( set, return_string = "", level = 1 )
      return_string += '<ul class="hierarchy">'
      set.items.each do |item|
        return_string += '<li>'
        return_string += evaluate_item(item, level)
        return_string += '</li>'
      end
      return_string += '</ul>'
    end

    def evaluate_ref(evaluation_id, item)
      eval_item = item.evaluation_items.find_by_evaluation_id(evaluation_id)
      return_string = ''
      
      unless eval_item.blank?
        eval_item.children.each do |child|
          return_string += '<ul class="reference">'
          return_string += '<li>'
          
          if child.set_item
            return_string += evaluate_item(child.set_item, child.level, eval_item)
          else
            return_string += evaluate_item(child.question, child.level, eval_item)
          end
          
          return_string += '</li>'
          return_string += '</ul>'
        end
      end
      return return_string
    end

    def evaluate_item(item, level, parent_item = nil)
      return_string = ''

      if item.class.name == "Survey::SurveyQuestion"
      	item_id = parent_item.question_set_item_id.to_s + '_opt'
      	item_id += parent_item.answer_text.gsub(',', '-') + '_q' + item.id.to_s
        return_string += '<span class="title item_'+item_id+'">' + hidden_field_tag("item_id", item_id)
        return_string += hidden_field_tag("question_id", item.id)
        return_string += hidden_field_tag("level", level)
        return_string += hidden_field_tag("object", @object) unless @object.nil?
        return_string += item.text + '</span>'
      elsif item.question_reference_type == "Survey::SurveyQuestionSet"
        return_string += '<span class="expand_or_collapse">'
        return_string +=		'<span class="expand">[+]</span>'
        return_string +=		'<span class="collapse">[-]</span>'
        return_string +=	'</span>'
        return_string +=  '<span class="title">' + item.question_reference.title.to_s + '</span>'
        return_string += evaluate_sets( item.question_reference, '', level )
      else
        return_string += '<span class="title item_'+item.id.to_s+'">' + hidden_field_tag( "item_id", item.id )
        return_string += hidden_field_tag( "level", level )
        return_string += hidden_field_tag( "object", @object ) unless @object.nil?
        return_string += item.question_reference.text.to_s + '</span>'

        return_string += evaluate_ref(@survey_evaluation.id, item) if @survey_evaluation
      end

      return return_string
    end
	end
end

app/views/survey/survey_evaluations/_evaluation_fields.html.erb
<%
  @parent = 0 if @parent.nil?
  condition = @question_set_item.nil? || @question_set_item.item_conditions.nil? ? 0 : 1
  index = (Time.now.to_f * 1000).to_i.to_s
  answer_text = @evaluation_item.nil? ? nil : @evaluation_item.answer_text
%>
<div id="evaluate_item_<%= @item_id %>" class="evaluation">
  <h4>Evaluate Question</h4>

  <div>
    <label>Question : </label><br/>
    <%= @question.text %>
  </div>

  <div>
    <label>Answer : </label><br/>
    <%
        answer_string = answer_text
        case @question.question_type
        when "Text Box"
          validation_text = "";
          @question.survey_question_validations.each do |val|
            validation = val.validation
            validation_text += validation.title.split("?")[0] + "(this"
            validation_text += ", " + val.validation_param_1 unless validation.param_1_caption.nil?
            validation_text += ", " + val.validation_param_2 unless validation.param_2_caption.nil?
            validation_text += "); "
          end

          validation_text += "return validate(this);"

          fields = text_field( @object + "["+index+"]", "answer_text",
            :value => answer_text, :class => "answer_text",
            :onblur => validation_text )

        when "Check Box"
          fields = ""
          i = 0
          answers = answer_text ? answer_text.split( ',' ) : []
          @question_selections.each do |selection|
            checked = answers.include? selection.id.to_s
            fields += check_box_tag( "selection_#{i}", selection.id, checked )
            fields += label_tag( "selection_#{i}", selection.text, :class => 'selection_label' ) + '<br/>'.html_safe
            i += 1
          end

          fields += hidden_field_tag( @object + "["+index+"][answer_text]",
            answer_string, :class => "selections" )

        when "Radio Button"
          fields = ""
          @question_selections.each do |selection|
            checked = (answer_text == selection.id.to_s )
            fields += radio_button_tag( @object + "["+index+"][answer_text]",
              selection.id, checked )

            fields += label_tag( "survey_evaluation_evaluation_items_attributes_#{index}_answer_text",
              selection.text, :class => 'selection_label' ) + '<br/>'.html_safe
          end

        when "Drop Down"
          fields = collection_select( @object + "["+index+"]", "answer_text",
            @question_selections, :id, :text, { :selected => answer_string } )
        when "Text Box(Date)"
                date_value = answer_text unless answer_text.nil?
                fields = text_field( @object + "["+index+"]", "answer_text",
                  :class => "datepicker", :value => date_value, :readonly => true )
        end
    %>
    <%= hidden_field_tag( @object + "["+index+"][id]", @evaluation_item.id ) if @evaluation_item %>
    <%= hidden_field_tag( @object + "["+index+"][question_set_item_id]", @question_set_item.id ) if @question_set_item %>
    <%= hidden_field_tag( @object + "["+index+"][question_id]", @question.id ) %>
    <%= fields.html_safe %>
    <!--<%= hidden_field_tag( @object + "["+index+"][parent_id]", @parent ) %>-->
    <%= hidden_field_tag( @object + "["+index+"][level]", @level, :class => "level" ) %>
    <%= hidden_field_tag( "condition", condition ) %>
  </div>
  
  <div>
    <%= button_tag "Evaluate", :class => 'evaluate_question' %>
  </div>
</div>

app/views/survey/survey_evaluations/_evaluation_items.html.erb
<% @survey_question_sets.each do |set| %>
<ul id="set_<%= set.id %>">
  <% set.evaluations.each do |evaluation| %>
    <li>
      <span>
        <%= evaluation.id %>
      </span>
      
      <span class="actions">
        <%= link_to "Edit", survey_evaluation_path(evaluation), :remote => true %>
      </span>

      <span class="actions">
        <%= link_to "Delete", survey_evaluation_path(evaluation), :method => :delete %>
      </span>
    </li>
  <% end %>
</ul>
<% end %>

app/views/survey/survey_evaluations/_evaluations.html.erb
<div id="set_<%= @survey_question_set.id %>" class="evaluation_container">
  <table id="set_table_<%= @survey_question_set.id %>" class="evaluations" >
    <thead>
            <th>Evaluation</th>
            <th>Status</th>
            <th class="time">Start time</th>
            <th>actions</th>
    </thead>
    
    <tbody>

      <% @evaluations.each do |evaluation| %>
        <tr>
          <td>
            <%= evaluation.id %>
          </td>
          <td>
            <%= evaluation.status %>
          </td>
          <td class="time">
            <%= evaluation.created_at %>
          </td>
          <td class="actions">
            <%= link_to "Edit", edit_survey_evaluation_path(evaluation), :remote => true,
              :class => "edit" %>
            <%= link_to "Delete", survey_evaluation_path(evaluation), :method => :delete,
              :confirm => 'Are you sure?', :class => "delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
  </table>
</div>

app/views/survey/survey_evaluations/_survey_question_set.html.erb
<% @survey_question_sets.each do |survey_question_set| %>
  <tr>
    <td id="<%= survey_question_set.id %>" class="evaluation_title" title="Click to see the evaluations made on this Question Set">
      <%= survey_question_set.title %>
    </td>
    <td>
      <%= survey_question_set.version %>
    </td>
    <td>
      <%= form_tag '/survey/survey_evaluations', :remote => true do %>
        <%= hidden_field_tag "question_set_id", survey_question_set.id %>
        <%= hidden_field_tag "status", "started" %>
        <%= submit_tag("New") %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/survey/survey_evaluations/add_condition_reference.js.erb
if($('span.item_<%= @question_set_item.id %>').parent().children('ul.reference').length > 0)
	$('span.item_<%= @question_set_item.id %>').parent().children('ul.reference').remove();

<%
  unless @conditions.blank?
    @conditions.each do |condition|
      return_str = '<ul class="reference"><li>'
      if condition.reference_type == 1
        item_id = @question_set_item.id.to_s + '_opt'
      	item_id += @selected_value + '_q' + condition.reference_id.to_s
        question = Survey::SurveyQuestion.find( condition.reference_id )
        return_str += '<span class="title item_'+item_id+'">' + hidden_field_tag( "item_id", item_id )
        return_str += hidden_field_tag( "question_id", condition.reference_id )
        return_str += hidden_field_tag( "level", @level )
        return_str += hidden_field_tag( "object", @object )
        return_str += question.text + '</span>'
      else
        set = Survey::SurveyQuestionSet.find( condition.reference_id )
        return_str += '<span class="expand_or_collapse">'
        return_str += '<span class="expand">[+]</span><span class="collapse">[-]</span>'
        return_str += '</span>'
        return_str += '<span class="title">' + set.title + '</span>'
        return_str += evaluate_sets( set, '', @level )
      end
      
      return_str += '</li></ul>'
%>
  $('span.item_<%= @question_set_item.id %>').parent().append('<%= return_str.html_safe %>');
<%
    end
  end

  if !@errors.blank? && @conditions.blank?
%>
    $('#evaluate_item_<%= @question_set_item.id %>').find('input[type=text]').css('border', '1px solid red');
<% end %>

app/views/survey/survey_evaluations/edit.html.erb
<h1>Edit Survey Evaluation</h1>
<%= form_for @survey_evaluation do |f| %>
  <%= f.hidden_field :status, :value => "completed" %>
  <%= hidden_field_tag :eval_id, @survey_evaluation.id %>
  <div class="question_tree">
    <%= evaluate_sets( @survey_question_set ).html_safe %>
  </div>

  <div id="selected_question">

  </div>

  <div class="actions clr_float">
    <%= f.submit "save", :class => "save_survey_evaluation" %>
  </div>
<% end %>

app/views/survey/survey_evaluations/edit.js.erb
$('body').addClass('survey_evaluations');
$.facebox("<%=  escape_javascript( render :template => '/survey/survey_evaluations/edit.html.erb' ) %>");
$('#edit_overlay').remove();

app/views/survey/survey_evaluations/evaluate_question.js.erb
var item_id = '<%= @item_id %>';
var item_opt_id = item_id.substring(0, item_id.lastIndexOf('_'));
if($('#selected_question .evaluation').length > 0) {
	if($('#selected_question div[id^="evaluate_item_'+item_opt_id+'"]').length <= 0) {
  	item_id_opt = item_opt_id.substring(0, item_opt_id.lastIndexOf('_')+3)

  	if($('#selected_question div[id^="evaluate_item_'+item_id_opt+'"]').length > 0) {
  	  $('#selected_question div[id^="evaluate_item_'+item_id_opt+'"]').remove();
  	}
	}
}

$('#selected_question').append("<%= escape_javascript( render 'evaluation_fields' ) %>");

/*Initialize datepicker*/
$('.datepicker').datepicker({
  dateFormat: 'dd/mm/yy',
  showOn: "both",
  buttonImage: '/assets/survey/calendar.gif',
  buttonImageOnly: true
});
$('#edit_overlay, #evaluation_overlay').remove();

app/views/survey/survey_evaluations/get_evaluations.js.erb
$('body').addClass('survey_evaluations');
$.facebox("<%= escape_javascript( render 'evaluations' ) %>");
$('#set_table_<%= @survey_question_set.id %>').dataTable({
  "aoColumns": [
                  null,
                  null,
                  null,
                  { "bSortable": false }
               ]
});
$('#edit_overlay').remove();

app/views/survey/survey_evaluations/index.html.erb
<div class="section survey_evaluation">
  <h1>Survey Evaluation</h1>

  <div class="categories">
    <%= link_to "All",
      { :controller => "survey_questions", :action => "get_questions",
        :category => "all", :item => "survey_evaluation" },
      :remote => true, :id => "cat-all" %>

    <div class="add_category">
      <%= link_to "Add", new_survey_question_category_path, :remote => true,
        :title => "Add a new category" if current_user.admin? %>
    </div>

    <%= render 'survey/survey_question_categories/question_categories', :parent => nil,
      :item => 'survey_evaluation' %>
  </div>

  <div class="list_content">
    <p class="description">
      *Click on a Question Set to see the list of evaluations made
    </p>
    <table id="evaluation_list" class="survey_evaluations">
      <thead>
        <th>Question Set</th>
        <th>Version</th>
        <th>Actions</th>
      </thead>

      <tbody>
        <%= render "survey_question_set" %>
      </tbody>
    </table>
  </div>
</div>