config/routes.rb
Survey::Engine.routes.draw do
	resources :survey_question_categories
	resources :survey_question_set_items
	resources :survey_validations
	resources :survey_questions do
		collection do
			get 'get_questions'
		end
	end
	resources :survey_question_sets do
		collection do
			get 'get_question_sets'
			get 'add_condition'
		end
	end
	resources :survey_evaluations, :except => [ :new, :show ] do
		collection do
			get 'evaluate_question'
			get 'add_condition_reference'
			get 'get_evaluations'
		end
	end
	root :to => 'survey_evaluations#index'
end

app/models/survey/survey_evaluation.rb
#app/models/survey_evaluation.rb
module Survey
	class SurveyEvaluation < ActiveRecord::Base
		set_table_name "survey_evaluations"

		attr_accessible :question_set_id, :status, :user_id, :evaluation_items_attributes

		has_many :evaluation_items, :class_name => "SurveyEvaluationItem", :foreign_key => :evaluation_id

		belongs_to :question_set, :class_name => "SurveyQuestionSet", :foreign_key => :question_set_id
    belongs_to :user, :class_name => USER_RESOURCE

		accepts_nested_attributes_for :evaluation_items,
																	:reject_if => proc { |attributes| attributes['answer_text'].blank? }

		validates :question_set_id, :presence => true
		#validates :status, :presence => true, :inclusion => { :in => ['started', 'completed']}
		validates_associated :evaluation_items
	end
end

app/models/survey/survey_question_category.rb
#app/models/survey/survey_question_category.rb

module Survey
	class SurveyQuestionCategory < ActiveRecord::Base
		set_table_name "survey_question_categories"

		attr_accessible :title, :parent_id

		has_many :children, :class_name => "SurveyQuestionCategory", :dependent => :destroy, :foreign_key => "parent_id"
		belongs_to :parent, :class_name => "SurveyQuestionCategory"
		has_many :questions, :class_name => "SurveyQuestion", :foreign_key => "question_category_id", :dependent => :destroy

		#scope :parents, where("parent_id IS NULL")

		validates :title, :presence => true, :length => { :maximum => 50 }, :uniqueness => { :case_sensitive => false }

		def descendants
		  all = []
		  self.children.each do |category|
		    all << category.id
		    root_children = category.descendants.flatten
		    all << root_children unless root_children.empty?
		  end
		  return all.flatten
		
		end

	end
end

app/models/survey/survey_question_selection.rb
#app/models/survey/survey_question_selection.rb

module Survey
	class SurveyQuestionSelection < ActiveRecord::Base
		set_table_name "survey_question_selections"

		attr_accessible :question_id, :text

		belongs_to :question, :class_name => "SurveyQuestion", :foreign_key => :question_id

		has_many :condition_selections, :class_name => "SurveyQuestionSetItemConditionSelection",
						 :foreign_key => :condition_id
		has_many :item_conditions, :class_name => "SurveyQuestionSetItemCondition", :through => :condition_selections
	
		validates :question, :presence => true
		validates :text, :presence => true
	end
end

app/models/survey/survey_question_set_item_condition_selection.rb
#app/models/survey/survey_question_set_item_condition_selection.rb

module Survey
	class SurveyQuestionSetItemConditionSelection < ActiveRecord::Base
		set_table_name "survey_question_set_item_condition_selections"

		attr_accessible :condition_id, :selection_id

		belongs_to :item_condition, :class_name => "SurveyQuestionSetItemCondition", :foreign_key => :condition_id
		belongs_to :selection, :class_name => "SurveyQuestionSelection", :foreign_key => :selection_id

		validates :item_condition, :presence => true
		validates :selection_id, :presence => true
	end
end

app/controllers/survey/application_controller.rb
module Survey
  class ApplicationController < ::ApplicationController
    protect_from_forgery

    protected

      def redirect_unless_logged_in
        if defined?(super)
          super
        else
          unless user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          end
        end
      end

      def redirect_unless_admin
        if defined?(super)
          super
        else
          if !user_signed_in?
            redirect_to main_app.new_user_session_path, :notice => 'Please log in.'
          elsif !current_user.admin?
            redirect_to main_app.root_path, :notice => 'You do not have permission to view this page.'
          end
        end
      end
  end
end

app/controllers/survey/survey_evaluations_controller.rb
#app/controllers/survey_evaluations_controller.rb

module Survey
	class SurveyEvaluationsController < ApplicationController
		before_filter :add_class
		before_filter :redirect_unless_logged_in

		unloadable #marks the class for reloading inbetween requests.

    def index
      @survey_question_sets = SurveyQuestionSet.where( "published = ? AND question_set_type = ?", true, 'Assembly')
      @survey_question_categories = SurveyQuestionCategory.all
    end

    def create
      @survey_question_set = SurveyQuestionSet.find( params[:question_set_id] )
      @survey_evaluation = @survey_question_set.evaluations.create!( {:status => params[:status], :user_id => current_user.id} )

      render :edit
    end

    def edit
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_question_set = @survey_evaluation.question_set

      respond_to do |format|
        format.js
        format.html
      end
    end

    def update
      @survey_evaluation = SurveyEvaluation.find( params[:id] )

      if @survey_evaluation.update_attributes( params[:survey_evaluation] )
        flash[:notice] = "Survey Evaluation updated successfully!"
        redirect_to survey_evaluations_path
      else
        @survey_evaluation = SurveyEvaluation.find( params[:id] )
        @survey_question_set = @survey_evaluation.question_set
        render 'edit'
      end
    end

    def destroy
      @survey_evaluation = SurveyEvaluation.find( params[:id] )
      @survey_evaluation.destroy
      flash[:notice] = "Survey Evaluation successfully destroyed!"
      redirect_to survey_evaluations_path
    end

    def evaluate_question
      items = params[:item_id].include?('_') ? nil : SurveyQuestionSetItem.where(:id => params[:item_id])
      @level = params[:level] ? params[:level] : 1
      @object = params[:object].nil? ? "survey_evaluation[evaluation_items_attributes]" : params[:object] + "[children_attributes]"
      @evaluation = SurveyEvaluation.find( params[:eval_id] ) if params[:eval_id]

      unless items.blank?
        @question_set_item = items.first
        if @question_set_item.question_reference_type == "Survey::SurveyQuestion"
          @question = @question_set_item.question_reference
        end

        if @evaluation
          @evaluation_item = @evaluation.evaluation_items.where('question_id = ? AND level = ? AND question_set_item_id = ?', @question.id, @level, @question_set_item.id ).first
        else
          @evaluation_item = SurveyEvaluationItem.where('question_id = ? AND level = ? AND question_set_item_id = ?',
                                                      @question.id, @level, @question_set_item.id ).first
        end
      end

      @question = SurveyQuestion.find( params[:question_id] ) if params[:question_id]
      @item_id = params[:item_id]

      if @evaluation_item.blank?
      	if @evaluation && params[:question_id]
      		@evaluation_item = @evaluation.evaluation_items
      			.where('question_id = ? AND level = ? AND question_set_item_id IS NULL',
      				 params[:question_id], @level ).first
      	else
        	@evaluation_item = SurveyEvaluationItem.new
        end
      end

      if @question.question_type == "Text Box"
        @question_validations = @question.survey_question_validations
      else
        @question_selections = @question.selections
      end

      respond_to do |format|
        format.js
      end

    end

    def add_condition_reference
      @question_set_item = SurveyQuestionSetItem.find( params[:item_id] )
      eval_item = SurveyEvaluationItem.new
      @conditions = []
      @level = params[:level].to_i + 1;
      @object = params[:object]
      @selected_value = params[:text].kind_of?(Array) ? params[:text].join('-') : params[:text]
      unless @question_set_item.nil?
        @valid = true
        @errors = []
        @question_set_item.item_conditions.each do |condition|
          if @question_set_item.question_reference.question_type == "Text Box"
            @param_list = []
            @param_list << params[:text]
            condition.condition_validations.each do |condition_val|
              @param_list << condition_val.validation_param_1 if condition_val.validation_param_1
              @param_list << condition_val.validation_param_2 if condition_val.validation_param_2
              validation_method = condition_val.item_validation.title
              unless eval_item.send validation_method, @param_list
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          
          elsif @question_set_item.question_reference.question_type != "Text Box(Date)"
          	selections = []
            condition.condition_selections.each do |condition_selection|
              selections << condition_selection.selection_id.to_s
            end
            
            if params[:text].kind_of?(Array)
              @size = params[:text].join(',')
              unless selections.sort! == params[:text].sort!
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            else
            	puts selections.inspect
            	puts '###'+params[:text]
              unless selections.include?(params[:text])
                @errors << "error"
                @valid = false
              else
              	@errors = []
              	@valid = true
              end
            end
            if @valid
              @conditions << condition
            end
          end
        end

      end
    end

    def get_evaluations
      @survey_question_set = SurveyQuestionSet.find(params[:set_id])
      @evaluations = @survey_question_set.evaluations.where('user_id = ?', current_user.id)

      respond_to do |format|
        format.js
      end
    end

    private

      def add_class
        @html_class = "survey_evaluation"
      end
  end
end

app/controllers/survey/survey_question_categories_controller.rb
#app/controllers/survey_question_categories_controller.rb

module Survey
	class SurveyQuestionCategoriesController < ApplicationController
		before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Categories"
      @survey_question_categories = SurveyQuestionCategory.all

      respond_to do |format|
        format.js { @set_id = params[:id] }
      end
    end

    def new
      @title = "Add Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.new
    end

    def create
      @survey_question_category =  SurveyQuestionCategory.new( params[:survey_question_category] )
      @facebox_id = params[:facebox_id]

      if @survey_question_category.save
        flash[:notice] = "Survey Question Category created successfully!"
        respond_to do |format|
          format.js {render :js => "window.location = '" + request.referer + "';"}
        end
      else
        @title = "Add Survey Question Categories"
        respond_to do |format|
          format.js { render 'new' }
        end
      end

    end

    def edit
      @title = "Edit Survey Question Categories"
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )
    end

    def update
      @survey_question_category = SurveyQuestionCategory.find( params[:id] )

      if @survey_question_category.update_attributes( params[:survey_question_category] )
        flash[:notice] = "Survey Question Category updated successfully!"
        redirect_to survey_question_categories_path
      else
        @title = "Edit Survey Question Categories"
        render 'edit'
      end

    end

    def get_conditions_form
      respond_to do |format|
        format.js
      end
    end

	end
end

app/controllers/survey/survey_question_set_items_controller.rb
#app/controllers/survey_question_set_items_controller.rb

module Survey
	class SurveyQuestionSetItemsController < ApplicationController
    before_filter :redirect_unless_logged_in
    before_filter :redirect_unless_admin
    
		unloadable #marks the class for reloading inbetween requests.

    def index
      @title = "Survey Question Set Items"
      @survey_question_set_items = SurveyQuestionSetItem.all
    end

    def new
      @title = "Add Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.new
    end

    def create
      @survey_question_set_item = SurveyQuestionSetItem.new( params[:survey_question_set_item] )

      if @survey_question_set_item.save
        flash[:notice] = "Survey Question Set Item created successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Add Survey Question Set Item"
        render 'new'
      end

    end

    def edit
      @title = "Edit Survey Question Set Item"
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
    end

    def update
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )

      if @survey_question_set_item.update_attributes( params[:survey_question_set_item] )
        flash[:notice] = "Survey Question Set Item updated successfully!"
        redirect_to survey_question_set_items_path
      else
        @title = "Edit Survey Question Item"
        render 'edit'
      end
    end

    def destroy
      @survey_question_set_item = SurveyQuestionSetItem.find( params[:id] )
      @survey_question_set_item.destroy

      flash[:notice] = "Survey Question Set Item destroyed successfully!"
      redirect_to survey_question_set_items_path
    end

	end
end

app/controllers/survey/survey_validations_controller.rb
class SurveyValidationsController < ApplicationController
  def index
  end

end

app/helpers/survey/application_helper.rb
module Survey
	module ApplicationHelper

		# Return a title on a page
    def title
      base_title = "Mindfire Survey"
      if @title.nil?
        base_title
      else
        "#{@title} | #{base_title}"
      end
    end

    #return the logo of the app
    def logo
      image_tag( "rails.png", :alt => "Survey", :class => "round" )
    end

    #return the validations list
    def setup_question

      ( SurveyValidation.all - @survey_question.validations ).each do |validation|
        @survey_question.survey_question_validations.build(:validation => validation)
      end

      @survey_question.selections.build if @survey_question.selections.nil?
      @survey_question
      #question/tmp/clean-controllers.md.html
    end

    def evaluate_sets( set, return_string = "", level = 1 )
      return_string += '<ul class="hierarchy">'
      set.items.each do |item|
        return_string += '<li>'
        return_string += evaluate_item(item, level)
        return_string += '</li>'
      end
      return_string += '</ul>'
    end

    def evaluate_ref(evaluation_id, item)
      eval_item = item.evaluation_items.find_by_evaluation_id(evaluation_id)
      return_string = ''
      
      unless eval_item.blank?
        eval_item.children.each do |child|
          return_string += '<ul class="reference">'
          return_string += '<li>'
          
          if child.set_item
            return_string += evaluate_item(child.set_item, child.level, eval_item)
          else
            return_string += evaluate_item(child.question, child.level, eval_item)
          end
          
          return_string += '</li>'
          return_string += '</ul>'
        end
      end
      return return_string
    end

    def evaluate_item(item, level, parent_item = nil)
      return_string = ''

      if item.class.name == "Survey::SurveyQuestion"
      	item_id = parent_item.question_set_item_id.to_s + '_opt'
      	item_id += parent_item.answer_text.gsub(',', '-') + '_q' + item.id.to_s
        return_string += '<span class="title item_'+item_id+'">' + hidden_field_tag("item_id", item_id)
        return_string += hidden_field_tag("question_id", item.id)
        return_string += hidden_field_tag("level", level)
        return_string += hidden_field_tag("object", @object) unless @object.nil?
        return_string += item.text + '</span>'
      elsif item.question_reference_type == "Survey::SurveyQuestionSet"
        return_string += '<span class="expand_or_collapse">'
        return_string +=		'<span class="expand">[+]</span>'
        return_string +=		'<span class="collapse">[-]</span>'
        return_string +=	'</span>'
        return_string +=  '<span class="title">' + item.question_reference.title.to_s + '</span>'
        return_string += evaluate_sets( item.question_reference, '', level )
      else
        return_string += '<span class="title item_'+item.id.to_s+'">' + hidden_field_tag( "item_id", item.id )
        return_string += hidden_field_tag( "level", level )
        return_string += hidden_field_tag( "object", @object ) unless @object.nil?
        return_string += item.question_reference.text.to_s + '</span>'

        return_string += evaluate_ref(@survey_evaluation.id, item) if @survey_evaluation
      end

      return return_string
    end
	end
end

app/views/survey/survey_questions/_fields.html.erb
<%= render 'survey/shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.label :category %>
  <%= f.collection_select( :question_category_id, @categories, :id, :title ) %>
</div>

<div class="field">
  <%= f.label :text %>
  <%= f.text_field :text %>
</div>

<div class="field">
  <%= f.label :question_type %>
  <% @question_types = [ "Text Box", "Text Box(Date)", "Drop Down", "Check Box",
    "Radio Button" ] %>

  <%= f.select :question_type, @question_types %>
</div>

<div class="field">
  <label> Version :
    <% version = @survey_question.add_version %>
    <%= version %>
    <%= f.hidden_field :version, :value => version %>
  </label>

  <%= f.check_box :published, {}, true, false %>
  <%= f.label :published %>
  <%= f.check_box :active, {}, true, false %>
  <%= f.label :active %>
</div>

<div id="validations">
  <%= render 'validations', :f => f %>
</div>

<div id="selections">
  <%= render 'selections', :f => f %>
  <%= f.link_to_add "[+] Add A Selection", :selections %>
</div>

app/views/survey/survey_questions/_questions.html.erb
<ul>
  <li></li>
  <%
    i = (Time.now.to_f * 1000).to_i
    @condition_object = Hash.new
    @survey_questions.each do |question|

      checked = false
      item_id = nil
      unless @survey_question_set.nil?
        unless question.question_set_items.nil?
          @survey_question_set.items.each do |item|
            if item.question_reference_type == 'Survey::SurveyQuestion' && item.question_reference == question
              checked = true
              item_id = item.id
              @condition_object[item.id] = "survey_question_set[items_attributes][" + "#{i}" + "]"
              question_index[item.id] = i
              break
            end
          end
        end
      end
  %>

  <li class="question">

    <% if !@survey_question_set.published && !item_id.nil? %>
      <%= hidden_field "survey_question_set[items_attributes][" + "#{i}" + "]",
        "id", :value => item_id, :class => "id_field" %>

      <%= hidden_field "survey_question_set[items_attributes][" + "#{i}" + "]",
        "_destroy", :value => 0, :class => "destroy_field" %>
    <% end %>

    <%= hidden_field "survey_question_set[items_attributes][" + "#{i}" + "]",
      "question_reference_type", :value => "Survey::SurveyQuestion",
      :class => "item_type" %>

    <%= check_box_tag( "survey_question_set[items_attributes][" + "#{i}" + "][question_reference_id]",
      question.id, checked ) %>

    <%= label_tag( "survey_question_set_items_attriutes_#{i}_question_reference_id",
      question.text + " (" + question.version + ")" ) %>
    <% i += 1 %>

  </li>

<% end %>
</ul>

app/views/survey/survey_questions/_selection.html.erb
<div class="fields">

  <% if !@survey_question.published && ff.object.persisted? %>
    <%= ff.hidden_field :id, :class => "id_field" %>
    <%= ff.hidden_field :_destroy, :value => 0, :class => "destroy_field" %>
  <% end %>

  <%= ff.text_field :text%>
  <%= link_to "[-] Remove", "#", :class => 'remove_link' %>
</div>

app/views/survey/survey_questions/_selections.html.erb
<%= f.label "Add Selections" %>

<%= f.fields_for :selections do |ff| %>
  <%= render 'selection', :ff => ff %>
<% end %>

app/views/survey/survey_questions/_survey_question.html.erb
<tr>

  <% html_class = survey_question.published ? 'edit edit_published_question' : 'edit' %>

  <td class="question_title">
    <%=	survey_question.text %>
  </td>

  <td>
    <%= survey_question.version %>
  </td>

  <td>
    <%= survey_question.published ? 'published' : 'draft' %>
  </td>

  <td class="actions">
    <%= link_to "Edit", edit_survey_question_path( survey_question ),
      :remote => true, :class => html_class %>

    <% unless survey_question.published %>
      <%= link_to "Delete", survey_question_path( survey_question ),
        :method => :delete, :confirm => 'Are you sure?', :class => "delete" %>
    <% else %>
      <%= link_to "Delete", "#", :onclick => "return false",
        :class => "disabled_delete", :title => "Disabled" %>
    <% end %>

  </td>
</tr>

app/views/survey/survey_questions/_validations.html.erb
<%= f.label "Add Validations" %>

<div id="validation_list">
  <%= f.fields_for :survey_question_validations do |ff| %>
    <span class="validation_title">
      <% html_class = ff.object.persisted? ? 'published' : '' %>

      <% if ff.object.persisted? && !@survey_question.published %>
        <%= ff.hidden_field :id, :class => "id_field" %>
      <% end %>

      <%= ff.check_box :_destroy,
        {:checked => ff.object.persisted?, :class => html_class }, '0', '1' %>

      <%= ff.label :__destroy, ff.object.validation.title %>
      <%= ff.hidden_field :validation_id %>
    </span>

    <% unless ff.object.validation.param_1_caption.nil? %>
      <span class="validation_params">
        Validation Parameters: <br/>

        <div>
          <%= ff.label :validation_param_1, ff.object.validation.param_1_caption %>
          <%= ff.text_field :validation_param_1, :size => 2, :disabled => !ff.object.persisted? %>
        </div>

        <% unless ff.object.validation.param_2_caption.nil? %>
          <div>
            <%= ff.label :validation_param_2, ff.object.validation.param_2_caption %>
            <%= ff.text_field :validation_param_2, :size => 2, :disabled => !ff.object.persisted? %>
          </div>
        <% end %>
      </span>

    <% end %>

  <% end %>
</div>

app/views/survey/survey_questions/edit.js.erb
$('#edit_overlay').remove();

<% if @survey_question.published %>
  if (confirm("The Question is published! Do you want to create a new version?")){
<% end %>
    <% if @facebox_id %>
      $.facebox("<%= escape_javascript( render :template => '/survey/survey_questions/edit.html.erb' ) %>", false, "<%= @facebox_id %>");
    <% else %>
      $.facebox("<%= escape_javascript( render :template => '/survey/survey_questions/edit.html.erb' ) %>");
    <% end %>

    $('.facebox').attr('tabindex', '1000').focus();
    $('.fields').parent('.fields').children('input[type="hidden"]').remove();
    if ($('#survey_question_question_type').length > 0) {
      question_type = $('#survey_question_question_type').val();
      if (question_type == "Text Box") {
        $('#selections').css('display', 'none');
        $('#selections').children('.fields').children('input').attr('disabled', 'disabled');
      }
      else if (question_type == "Text Box(Date)") {
        $('#validations, #selections').css('display', 'none');
        $('#validations').children('.fields').children('input').attr('disabled', 'disabled');
        $('#selections').children('.fields').children('input').attr('disabled', 'disabled');
      }
      else {
        $('#validations').css('display', 'none');
        $('#validations').children('.fields').children('input').attr('disabled', 'disabled');
      }
    }

<% if @survey_question.published %>
  }
<% end %>

$('.published').parent('span').next('input[type=hidden]').remove();

app/views/survey/survey_questions/get_questions.html.erb
<%= @survey_questions.nil? ? "Nil" : "Content" %>
<%= render 'survey/survey_questions/questions' %>

app/views/survey/survey_questions/get_questions.js.erb
<% unless @survey_question_set.nil? %>
  $("#show_questions").html("<%= escape_javascript( render 'survey/survey_questions/questions' ) %>");
  $("#show_question_sets").html("<%= escape_javascript( render 'survey/survey_question_sets/question_sets' ) %>");

  $('#show_selected_items ul.items li input[type="checkbox"]:checked').each(function(){
    chkbox = $(".show_category_items input[type=checkbox][value="+$(this).val()+"]");

    if($(chkbox).length > 0 && ($(this).prev('.item_type').val() == "Survey::SurveyQuestion"))
      $(".show_category_items li.question input[type=checkbox][value="+$(this).val()+"]").attr('checked', 'checked');
    else
      $(".show_category_items li.question_set input[type=checkbox][value="+$(this).val()+"]").attr('checked', 'checked');
  });
<% else %>

  <% if @item == 'survey_evaluation' %>
    $("#evaluation_list_wrapper").remove();

    return_str = '<table id="evaluation_list" class="survey_evaluations">\
                    <thead>\
                      <th>Question Set</th>\
                      <th>Version</th>\
                      <th>Actions</th>\
                    </thead>\
                    <tbody>\
                      <%= escape_javascript(render "survey/survey_evaluations/survey_question_set") %>\
                    </tbody>\
                  </table>';

    $(".list_content").append(return_str);
    $('#evaluation_list').dataTable({
      "aoColumns": [
                      null,
                      null,
                      { "bSortable": false }
                   ]
    });

  <% else %>
    $("div.add_question, div.add_question_set").next().remove();

    return_str = '<table id="questions_list" class="survey_questions display">\
                    <thead>\
                      <th>Title</th>\
                      <th>Version</th>\
                      <th>Status</th>\
                      <th>Actions</th>\
                    </thead>\
                    <tbody>';

    <% if @item == 'survey_question' %>
      return_str += '<%= escape_javascript(render @survey_questions) %>';
    <% else %>
      return_str += '<%= escape_javascript(render @survey_question_sets) %>';
    <% end %>

    return_str += '</tbody>\
                  </table>';

    $('.list_content').append(return_str);

    $('#questions_list').dataTable({
      "aoColumns": [
                      null,
                      null,
                      null,
                      { "bSortable": false }
                   ]
    });
  <% end %>
<% end %>

app/views/survey/survey_questions/index.html.erb
<div class="section survey_questions">
  <h1>Survey Questions</h1>

  <div class="categories">
    <%= link_to "All",
      { :action => "get_questions", :category => "all", :item => "survey_question" },
      :remote => true, :id => "cat-all" %>

    <div class="add_category">
      <%= link_to "Add", new_survey_question_category_path, :remote => true %>
    </div>

    <%= render 'survey/survey_question_categories/question_categories', :parent => nil,
      :item => "survey_question" %>
  </div>

  <div class="list_content">
    <div class="add_question">
      <%= link_to "Add", new_survey_question_path, :remote => true %>
    </div>

    <table id="questions_list" class="survey_questions display">
      <thead>
        <th>Title</th>
        <th>Version</th>
        <th>Status</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <%= render @survey_questions %>
      </tbody>
    </table>
  </div>
</div>

app/views/survey/survey_questions/new.html.erb
<h1>Add Survey Question</h1>

<%= nested_form_for setup_question, :remote => true do |f| %>
  <%= render 'fields', :f => f %>

  <div class = "actions">
    <%= f.submit "Create Question" %>
  </div>

<% end %>

app/views/survey/survey_questions/new.js.erb
<% if @facebox_id %>
  $.facebox("<%= escape_javascript( render :template => '/survey/survey_questions/new.html.erb' ) %>", false, "<%= @facebox_id %>");
<% else %>
  $.facebox("<%= escape_javascript( render :template => '/survey/survey_questions/new.html.erb' ) %>");
<% end %>

$('.facebox').attr('tabindex', '1000').focus();
$('.fields').parent('.fields').children('input[type="hidden"]').remove();
if ($('#survey_question_question_type').length > 0)
{
  if ($('#survey_question_question_type').val() != "Text Box")
  {
    $('#validations').css('display', 'none');
    $('#validations').children('.fields').children('input').attr('disabled', 'disabled');
  }
  else
  {
    $('#selections').css('display', 'none');
    $('#selections').children('.fields').children('input').attr('disabled', 'disabled');
  }
}

$('#edit_overlay').remove();

app/views/survey/survey_questions/show.html.erb
<h1>Survey Question</h1>

<div class="questions">
  <div>
    <label>Text :</label>
    <%= @survey_question.text %>
  </div>

  <div>
    <label>Type :</label>
    <%= @survey_question.question_type %>
  </div>

  <div>
    <label>Version :</label>
    <%= @survey_question.version %>
  </div>

  <% if @survey_question.question_type == "Text Box" %>

    <div>
      <label>Validation :</label><br />
      <% @survey_question.survey_question_validations.each do |ques_val| %>
        <%= ques_val.validation.title %> <br />
      <% end %>
    </div>

  <% else %>

    <div>
      <label>Selections :</label><br />
      <% @survey_question.selections.each do |selection| %>
        <%= selection.text %> <br />
      <% end %>
    </div>
  <% end %>

</div>

app/views/survey/survey_questions/validations.html.erb
<%= f.label "Add Validations" %>

<%= f.fields_for :survey_question_validations do |ff| %>

  <div class="fields">
    <span>
      <%= ff.check_box :_destroy, {:checked => ff.object.persisted?}, '0', '1' %>
      <%= ff.label :_destroy, ff.object.validation.title %>
      <%= ff.hidden_field :validation_id %>
    </span>

    <% unless ff.object.validation.param_1_caption.nil? %>
      <span>
        <%= ff.label :validation_param_1, ff.object.validation.param_1_caption %>
        <%= ff.text_field :validation_param_1, :size => 2 %>
      </span>
    <% end %>

    <% unless ff.object.validation.param_2_caption.nil? %>
      <span>
        <%= ff.label :validation_param_2, ff.object.validation.param_2_caption %>
        <%= ff.text_field :validation_param_2, :size => 2 %>
      </span>
    <% end %>

  </div>
<% end %>